return {                                                                                                                                                                                                                                                                │AE-E5AE-4164-81DE-B4DCD788485D","directory":"/lfs/env
  -- "nvim-telescope/telescope.nvim",                                                                                                                                                                                                                                   │d/data/WBC/WBC_CONSISTENCY_IDM_MCP_DBS/in","matchRule
  -- dependencies = {                                                                                                                                                                                                                                                   │s":{".*\\.csv":1},"continueWithoutFiles":false,"ready
  --   "nvim-lua/plenary.nvim",                                                                                                                                                                                                                                         │CheckerType":"POLLING"},"engineInstanceId":"SYDMCP004
  -- },                                                                                                                                                                                                                                                                 │LX.MBK.01","environment":"envd","event":"ADD","histor
  "nvim-telescope/telescope.nvim",                                                                                                                                                                                                                                      │yId":"E4B3742E-56AF-4E4B-9D66-F31E10543E07","inSyncWi
  dependencies = {                                                                                                                                                                                                                                                      │thTicket":true,"jobId":"WBC_CONSISTENCY_IDM_MCP_DBS",
    {                                                                                                                                                                                                                                                                   │"source":"ADHOC","sourceSystemId":"tomcat|sydmcp005lx
      "nvim-telescope/telescope-live-grep-args.nvim",                                                                                                                                                                                                                   │.fxdms.net","status":"ACTIVE","ticketId":"E4B3742E-56
      -- This will not install any breaking changes.                                                                                                                                                                                                                    │AF-4E4B-9D66-F31E10543E07"}
      -- For major updates, this must be adjusted manually.                                                                                                                                                                                                             │
      -- version = "^1.0.0",                                                                                                                                                                                                                                            │{"actions":[{"actionId":"46991C2E-9E94-4F26-9B9E-93BC
    },                                                                                                                                                                                                                                                                  │2991CC9A","actionType":"MCP_JOB","classRules":{},"con
  },                                                                                                                                                                                                                                                                    │textRules":{".*\\.csv":"IDM_FILE"},"priorityRules":{}
  config = function()                                                                                                                                                                                                                                                   │}],"clientId":"WBC","configId":"786F6EAE-E5AE-4164-81
    local telescope = require("telescope")                                                                                                                                                                                                                              │DE-B4DCD788485D","configType":"WEBSERVICE","dateCreat
    local lga_actions = require("telescope-live-grep-args.actions")                                                                                                                                                                                                     │ed":"2025-04-17 10:05:04","description":"Process IDM 
                                                                                                                                                                                                                                                                        │Data","directoryConfig":{"allowMatchCountOverflow":tr
    -- first setup telescope                                                                                                                                                                                                                                            │ue,"collisionDetectionType":"NONE","configId":"786F6E
    telescope.setup({                                                                                                                                                                                                                                                   │AE-E5AE-4164-81DE-B4DCD788485D","directory":"/lfs/env
      -- your config                                                                                                                                                                                                                                                    │d/data/WBC/WBC_CONSISTENCY_IDM_MCP_DBS/in","matchRule
      extensions = {                                                                                                                                                                                                                                                    │s":{".*\\.csv":1},"continueWithoutFiles":false,"ready
        live_grep_args = {                                                                                                                                                                                                                                              │CheckerType":"POLLING"},"engineInstanceId":"SYDMCP004
          auto_quoting = true, -- enable/disable auto-quoting                                                                                                                                                                                                           │LX.MBK.01","environment":"envd","event":"ADD","histor
          -- define mappings, e.g.                                                                                                                                                                                                                                      │yId":"207CEE21-05F2-4C57-AF57-5B56191EB4E3","inSyncWi
          mappings = { -- extend mappings                                                                                                                                                                                                                               │thTicket":true,"jobId":"WBC_CONSISTENCY_IDM_MCP_DBS",
            i = {                                                                                                                                                                                                                                                       │"source":"ADHOC","sourceSystemId":"tomcat|sydmcp005lx
              ["<C-k>"] = lga_actions.quote_prompt(),                                                                                                                                                                                                                   │.fxdms.net","status":"ACTIVE","ticketId":"207CEE21-05
              ["<C-i>"] = lga_actions.quote_prompt({ postfix = " --iglob " }),                                                                                                                                                                                          │F2-4C57-AF57-5B56191EB4E3"}
              -- freeze the current list and start a fuzzy search in the frozen list                                                                                                                                                                                    │
              ["<C-space>"] = lga_actions.to_fuzzy_refine,                                                                                                                                                                                                              │{"actions":[{"actionId":"46991C2E-9E94-4F26-9B9E-93BC
            },                                                                                                                                                                                                                                                          │2991CC9A","actionType":"MCP_JOB","classRules":{},"con
          },                                                                                                                                                                                                                                                            │textRules":{".*\\.csv":"IDM_FILE"},"priorityRules":{}
          -- ... also accepts theme settings, for example:                                                                                                                                                                                                              │}],"clientId":"WBC","configId":"786F6EAE-E5AE-4164-81
          -- theme = "dropdown", -- use dropdown theme                                                                                                                                                                                                                  │DE-B4DCD788485D","configType":"WEBSERVICE","dateCreat
          -- theme = { }, -- use own theme spec                                                                                                                                                                                                                         │ed":"2025-04-17 10:05:04","description":"Process IDM 
          -- layout_config = { mirror=true }, -- mirror preview pane                                                                                                                                                                                                    │Data","directoryConfig":{"allowMatchCountOverflow":tr
        },                                                                                                                                                                                                                                                              │ue,"collisionDetectionType":"NONE","configId":"786F6E
      },                                                                                                                                                                                                                                                                │AE-E5AE-4164-81DE-B4DCD788485D","directory":"/lfs/env
    })                                                                                                                                                                                                                                                                  │d/data/WBC/WBC_CONSISTENCY_IDM_MCP_DBS/in","matchRule
                                                                                                                                                                                                                                                                        │s":{".*\\.csv":1},"continueWithoutFiles":false,"ready
    -- then load the extension                                                                                                                                                                                                                                          │CheckerType":"POLLING"},"engineInstanceId":"SYDMCP004
    telescope.load_extension("live_grep_args")                                                                                                                                                                                                                          │LX.MBK.01","environment":"envd","event":"ADD","histor
  end,                                                                                                                                                                                                                                                                  │yId":"21984721-A612-4804-B717-41D64A54600C","inSyncWi
} 
